instrumentation:
  root: . # 执行的根目录
  extensions:
    - .js # 检查覆盖率的文件扩张名
  excludes:
    [
      '**/node_modules/**',
      '**/lib/reg/**',
      '**/lib/color.js',
      '**/lib/file.js',
      '**/lib/qrcode.js',
    ]
